rooms = [{:building_name => 'HRBB', :room_id => 126, :roomtype => 'Executive Meeting Room',
        :description=> 'nothing fancy', :booked=>true, :booker=>'estee', 
        :operate_start=> Time.parse("04-01-19 08:00"),
        :operate_end =>  Time.parse("04-01-19 19:00"), 
        :tech=>'Computers and Projector', :numpeople=>'1-4', :arrangement=> 'Tables and Chairs'},
        {:building_name => 'HRBB', :room_id => 124, :roomtype => 'Lecture Room',
        :description=> 'very comfy and homely', :booked=>true, :booker=> 'Admin', 
        :operate_start=> Time.parse("04-01-19 08:00"),
        :operate_end =>  Time.parse("04-01-19 19:00"),
        :tech=>'Projector', :numpeople=>'1', :arrangement=> 'Desks and Chairs'},
        {:building_name => 'HRBB', :room_id => 129, :roomtype => 'Lecture Room',
        :description=> 'good place to teach kids how to do coding', :booked=>true, :booker=> 'amy', 
        :operate_start=> Time.parse("04-01-19 08:00"),
        :operate_end =>  Time.parse("04-01-19 19:00"),
        :tech=>'Projector', :numpeople=>'101-500', :arrangement=> 'Chairs'},
        {:building_name => 'HRBB', :room_id => 113, :roomtype => 'Event Hall',
        :description=> 'TAMU peeps favourite', :booked=>true, :booker=> 'anthony', 
        :operate_start=> Time.parse("04-01-19 08:00"),
        :operate_end =>  Time.parse("04-01-19 19:00"),
        :tech=>'None', :numpeople=>'26-100', :arrangement=> 'Tables and Chairs'},
        {:building_name => 'HRBB', :room_id => 104, :roomtype => 'Lecture Room',
        :description=> ')*@(& Testing Description', :booked=>true, :booker=> 'jordan', 
        :operate_start=> Time.parse("04-01-19 08:00"),
        :operate_end =>  Time.parse("04-01-19 19:00"),
        :tech=>'Computers', :numpeople=>'5-25', :arrangement=> 'Desks and Chairs'},
        {:building_name => 'RDMC', :room_id => 111, :roomtype => 'Computer Lab',
        :description=> 'Get tech and funky', :booked=>false, 
        :operate_start=> Time.parse("04-01-19 08:00"),
        :operate_end =>  Time.parse("04-01-19 19:00"),
        :tech=>'Projector', :numpeople=>'1-4', :arrangement=> 'Chairs'},
        {:building_name => 'RDMC', :room_id => 112, :roomtype => 'Computer Lab',
        :description=> 'Youtube surfing', :booked=>false, 
        :operate_start=> Time.parse("04-01-19 08:00"),
        :operate_end =>  Time.parse("04-01-19 19:00"),
        :tech=>'Computers', :numpeople=>'1-4', :arrangement=> 'Tables and Chairs'},
        {:building_name => 'RDMC', :room_id => 211, :roomtype => 'Lecture Room',
        :description=> 'im sick of lecture rooms', :booked=>false, 
        :operate_start=> Time.parse("04-01-19 08:00"),
        :operate_end =>  Time.parse("04-01-19 19:00"),
        :tech=>'Computers and Projector', :numpeople=>'1-4', :arrangement=> 'Tables and Chairs'},
        {:building_name => 'RDMC', :room_id => 212, :roomtype => 'Lecture Room',
        :description=> 'QUANTUM COMPUTING AREA or maybe not', :booked=>false, 
        :operate_start=> Time.parse("04-01-19 08:00"),
        :operate_end =>  Time.parse("04-01-19 19:00"),
        :tech=>'Projector', :numpeople=>'1-4', :arrangement=> 'Tables and Chairs'},
        ]

rooms.each do |room|
    Room.create!(room)
end

users = [{:name => "Admin", :email => "rsquared.rooms@gmail.com",
        :password => "1234",
        :usertype => "Admin"},
        {:name => "Estee", :email => "estee.tsw@gmail.com",
        :password => "1234",
        :usertype => "Student"},
        {:name => "Kim", :email => "knguyen@gmail.com",
        :password => "1234",
        :usertype => "Student"},
        {:name => "Jordan", :email => "jmoore@gmail.com",
        :password => "1234",
        :usertype => "Student"},
        {:name => "Amy", :email => "ahughes@gmail.com",
        :password => "1234",
        :usertype => "Student"},
        {:name => "Anthony", :email => "avoneiff@gmail.com",
        :password => "1234",
        :usertype => "Student"}]

users.each do |user|
    User.create!(user)
end

bookings = [{:building_name => 'HRBB', :room_id => 1, :booker_id => 1, 
            :booker_name => 'Admin',
            :reason => "Admin just wanna sleep ok, nothing new or fancy", 
            :time_start=> DateTime.parse('3rd Feb 2019 04:05:06 PM'),
            :time_end=>DateTime.parse('5th Feb 2001 04:05:06 PM')},
            {:building_name => 'HRBB', :room_id => 2, :booker_id => 2, 
            :reason => "Estee just wanna sleep ok, nothing new or fancy", 
            :time_start=> DateTime.parse('3rd Feb 2019 04:05:06 PM'),
            :time_end=>DateTime.parse('5th Feb 2019 04:05:06 PM')},
            {:building_name => 'HRBB', :room_id => 3, :booker_id => 3, 
            :reason => "Kim just wanna sleep ok, nothing new or fancy", 
            :time_start=> DateTime.parse('3rd Feb 2019 04:05:06 PM'),
            :time_end=>DateTime.parse('5th Feb 2019 04:05:06 PM')},
            {:building_name => 'HRBB', :room_id => 4, :booker_id => 4, 
            :reason => "Jordan just wanna sleep ok, nothing new or fancy", 
            :time_start=> DateTime.parse('3rd Feb 2019 04:05:06 PM'),
            :time_end=>DateTime.parse('5th Feb 2019 04:05:06 PM')},
            {:building_name => 'HRBB', :room_id => 5, :booker_id => 5, 
            :reason => "Amy just wanna sleep ok, nothing new or fancy", 
            :time_start=> DateTime.parse('3rd Feb 2019 04:05:06 PM'),
            :time_end=>DateTime.parse('5th Feb 2019 04:05:06 PM')},
            {:building_name => 'RDMC', :room_id => 6, :booker_id => 6, 
            :reason => "Anthony just wanna sleep ok, nothing new or fancy", 
            :time_start=> DateTime.parse('5th Feb 2019 04:05:06 PM'),
            :time_end=>DateTime.parse('5th Feb 2019 04:05:06 PM')}
            ]
            
bookings.each do |booking|
    Booking.create!(booking)
end